/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppCreateOrganizationRouteImport } from './routes/_app.create-organization'
import { Route as AppOrgRouteImport } from './routes/_app._org'
import { Route as AppOrgIndexRouteImport } from './routes/_app._org.index'
import { Route as AppOrgSitesRouteImport } from './routes/_app._org.sites'
import { Route as AppOrgMembersRouteImport } from './routes/_app._org.members'
import { Route as AppOrgJobsRouteImport } from './routes/_app._org.jobs'
import { Route as AppOrgSitesNewRouteImport } from './routes/_app._org.sites.new'
import { Route as AppOrgSitesSiteIdRouteImport } from './routes/_app._org.sites.$siteId'
import { Route as AppOrgOrganizationSettingsRouteImport } from './routes/_app._org.organization.settings'
import { Route as AppOrgJobsNewRouteImport } from './routes/_app._org.jobs.new'
import { Route as AppOrgJobsJobIdRouteImport } from './routes/_app._org.jobs.$jobId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateOrganizationRoute = AppCreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSitesRoute = AppOrgSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgMembersRoute = AppOrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgJobsRoute = AppOrgJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSitesNewRoute = AppOrgSitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOrgSitesRoute,
} as any)
const AppOrgSitesSiteIdRoute = AppOrgSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AppOrgSitesRoute,
} as any)
const AppOrgOrganizationSettingsRoute =
  AppOrgOrganizationSettingsRouteImport.update({
    id: '/organization/settings',
    path: '/organization/settings',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgJobsNewRoute = AppOrgJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOrgJobsRoute,
} as any)
const AppOrgJobsJobIdRoute = AppOrgJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppOrgJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppOrgIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/create-organization': typeof AppCreateOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/jobs': typeof AppOrgJobsRouteWithChildren
  '/members': typeof AppOrgMembersRoute
  '/sites': typeof AppOrgSitesRouteWithChildren
  '/jobs/$jobId': typeof AppOrgJobsJobIdRoute
  '/jobs/new': typeof AppOrgJobsNewRoute
  '/organization/settings': typeof AppOrgOrganizationSettingsRoute
  '/sites/$siteId': typeof AppOrgSitesSiteIdRoute
  '/sites/new': typeof AppOrgSitesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof AppOrgIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/create-organization': typeof AppCreateOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/jobs': typeof AppOrgJobsRouteWithChildren
  '/members': typeof AppOrgMembersRoute
  '/sites': typeof AppOrgSitesRouteWithChildren
  '/jobs/$jobId': typeof AppOrgJobsJobIdRoute
  '/jobs/new': typeof AppOrgJobsNewRoute
  '/organization/settings': typeof AppOrgOrganizationSettingsRoute
  '/sites/$siteId': typeof AppOrgSitesSiteIdRoute
  '/sites/new': typeof AppOrgSitesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/_org': typeof AppOrgRouteWithChildren
  '/_app/create-organization': typeof AppCreateOrganizationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/_app/_org/jobs': typeof AppOrgJobsRouteWithChildren
  '/_app/_org/members': typeof AppOrgMembersRoute
  '/_app/_org/sites': typeof AppOrgSitesRouteWithChildren
  '/_app/_org/': typeof AppOrgIndexRoute
  '/_app/_org/jobs/$jobId': typeof AppOrgJobsJobIdRoute
  '/_app/_org/jobs/new': typeof AppOrgJobsNewRoute
  '/_app/_org/organization/settings': typeof AppOrgOrganizationSettingsRoute
  '/_app/_org/sites/$siteId': typeof AppOrgSitesSiteIdRoute
  '/_app/_org/sites/new': typeof AppOrgSitesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/create-organization'
    | '/settings'
    | '/accept-invitation/$invitationId'
    | '/jobs'
    | '/members'
    | '/sites'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/organization/settings'
    | '/sites/$siteId'
    | '/sites/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/create-organization'
    | '/settings'
    | '/accept-invitation/$invitationId'
    | '/jobs'
    | '/members'
    | '/sites'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/organization/settings'
    | '/sites/$siteId'
    | '/sites/new'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_app/_org'
    | '/_app/create-organization'
    | '/_app/settings'
    | '/accept-invitation/$invitationId'
    | '/_app/_org/jobs'
    | '/_app/_org/members'
    | '/_app/_org/sites'
    | '/_app/_org/'
    | '/_app/_org/jobs/$jobId'
    | '/_app/_org/jobs/new'
    | '/_app/_org/organization/settings'
    | '/_app/_org/sites/$siteId'
    | '/_app/_org/sites/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-organization': {
      id: '/_app/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof AppCreateOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_org': {
      id: '/_app/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_org/': {
      id: '/_app/_org/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/sites': {
      id: '/_app/_org/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppOrgSitesRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/members': {
      id: '/_app/_org/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppOrgMembersRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/jobs': {
      id: '/_app/_org/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppOrgJobsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/sites/new': {
      id: '/_app/_org/sites/new'
      path: '/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof AppOrgSitesNewRouteImport
      parentRoute: typeof AppOrgSitesRoute
    }
    '/_app/_org/sites/$siteId': {
      id: '/_app/_org/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AppOrgSitesSiteIdRouteImport
      parentRoute: typeof AppOrgSitesRoute
    }
    '/_app/_org/organization/settings': {
      id: '/_app/_org/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof AppOrgOrganizationSettingsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/jobs/new': {
      id: '/_app/_org/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppOrgJobsNewRouteImport
      parentRoute: typeof AppOrgJobsRoute
    }
    '/_app/_org/jobs/$jobId': {
      id: '/_app/_org/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppOrgJobsJobIdRouteImport
      parentRoute: typeof AppOrgJobsRoute
    }
  }
}

interface AppOrgJobsRouteChildren {
  AppOrgJobsJobIdRoute: typeof AppOrgJobsJobIdRoute
  AppOrgJobsNewRoute: typeof AppOrgJobsNewRoute
}

const AppOrgJobsRouteChildren: AppOrgJobsRouteChildren = {
  AppOrgJobsJobIdRoute: AppOrgJobsJobIdRoute,
  AppOrgJobsNewRoute: AppOrgJobsNewRoute,
}

const AppOrgJobsRouteWithChildren = AppOrgJobsRoute._addFileChildren(
  AppOrgJobsRouteChildren,
)

interface AppOrgSitesRouteChildren {
  AppOrgSitesSiteIdRoute: typeof AppOrgSitesSiteIdRoute
  AppOrgSitesNewRoute: typeof AppOrgSitesNewRoute
}

const AppOrgSitesRouteChildren: AppOrgSitesRouteChildren = {
  AppOrgSitesSiteIdRoute: AppOrgSitesSiteIdRoute,
  AppOrgSitesNewRoute: AppOrgSitesNewRoute,
}

const AppOrgSitesRouteWithChildren = AppOrgSitesRoute._addFileChildren(
  AppOrgSitesRouteChildren,
)

interface AppOrgRouteChildren {
  AppOrgJobsRoute: typeof AppOrgJobsRouteWithChildren
  AppOrgMembersRoute: typeof AppOrgMembersRoute
  AppOrgSitesRoute: typeof AppOrgSitesRouteWithChildren
  AppOrgIndexRoute: typeof AppOrgIndexRoute
  AppOrgOrganizationSettingsRoute: typeof AppOrgOrganizationSettingsRoute
}

const AppOrgRouteChildren: AppOrgRouteChildren = {
  AppOrgJobsRoute: AppOrgJobsRouteWithChildren,
  AppOrgMembersRoute: AppOrgMembersRoute,
  AppOrgSitesRoute: AppOrgSitesRouteWithChildren,
  AppOrgIndexRoute: AppOrgIndexRoute,
  AppOrgOrganizationSettingsRoute: AppOrgOrganizationSettingsRoute,
}

const AppOrgRouteWithChildren =
  AppOrgRoute._addFileChildren(AppOrgRouteChildren)

interface AppRouteChildren {
  AppOrgRoute: typeof AppOrgRouteWithChildren
  AppCreateOrganizationRoute: typeof AppCreateOrganizationRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgRoute: AppOrgRouteWithChildren,
  AppCreateOrganizationRoute: AppCreateOrganizationRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
